### ISSUE TITLE
Request for Review of Simulation - In cpu, the psw should have description upon hovering it.

### ISSUE THREAD

**Issue by Yashpal-0** [virtual-labs/exp-context-switching-iiith#2]
## *Experiment  Review Request*
Use this to get experiment reviewed.

1. *Exp Name*:
2. *Domain*:
3. *Lab Name*:
4. *Testing URL*:<!-- https://virtual-labs.github.io/${{ github.repository }} --!>

**Comment by Bhargavi-hash** [comment]
Done
